Add automated branch name detection and deployment to corresponding subfolder | sas | #101

diff --git a/images/node/bin/run-slack b/images/node/bin/run-slack
--- a/images/node/bin/run-slack
+++ b/images/node/bin/run-slack
@@ -8,17 +8,22 @@ if [[ -z "${GITHUB_SHA}" ]]; then
   exit 1
 fi
 
+if [[ -z "${GITHUB_REF}" ]]; then
+  echo 'Please provide the $GITHUB_REF environment variable.'
+  exit 1
+fi
+
 if [[ -z "${SLACK_WEBHOOK_URL}" ]]; then
   echo 'Please provide the $SLACK_WEBHOOK_URL environment variable.'
   exit 1
 fi
 
-PUIK_VERSION="v1"
-PUIK_SLACK_TEXT="Checkout https://ui.porsche.com/${PUIK_VERSION} :heart_eyes_cat:"
-PUIK_SLACK_ATTACHMENT="$(git log -1 --format=%s "${GITHUB_SHA}" | cat)"
-PUIK_CURL_STATUS="$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-type: application/json" --data "{\"text\": \"${PUIK_SLACK_TEXT}\", \"attachments\": [{\"text\": \"${PUIK_SLACK_ATTACHMENT}\"}]}" ${SLACK_WEBHOOK_URL})"
+P_ABBR_REF="$(git rev-parse --abbrev-ref ${GITHUB_REF})"
+P_SLACK_TEXT="Checkout https://ui.porsche.com/${P_ABBR_REF} :heart_eyes_cat:"
+P_SLACK_ATTACHMENT="$(git log -1 --format=%s "${GITHUB_SHA}" | cat)"
+P_CURL_STATUS="$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-type: application/json" --data "{\"text\": \"${P_SLACK_TEXT}\", \"attachments\": [{\"text\": \"${P_SLACK_ATTACHMENT}\"}]}" ${SLACK_WEBHOOK_URL})"
 
-if [[ "${PUIK_CURL_STATUS}" != 200 ]]; then
-  echo "Slack notification could not be sent (HTTP error code: ${PUIK_CURL_STATUS})."
+if [[ "${P_CURL_STATUS}" != 200 ]]; then
+  echo "Slack notification could not be sent (HTTP error code: ${P_CURL_STATUS})."
   exit 1
 fi
