Add doubles to prevent globbing and word splitting to run-release-npm script | sas | #214

diff --git a/docker/node/bin/run-release-npm b/docker/node/bin/run-release-npm
--- a/docker/node/bin/run-release-npm
+++ b/docker/node/bin/run-release-npm
@@ -5,7 +5,7 @@ set -o pipefail
 
 publish() {
   echo "task: [$(date)] \"publish\" $1"
-  result=$(yarn publish --non-interactive --registry=https://porscheui.jfrog.io/porscheui/api/npm/npm-local/ $1)
+  result=$(yarn publish --non-interactive --registry=https://porscheui.jfrog.io/porscheui/api/npm/npm-local/ "${1}")
 
   if [[ $result == *"Done"* ]]; then
     return 0 # true
@@ -28,17 +28,16 @@ is_version_published() {
 SCRIPT_DIR="$(cd `dirname ${0}` && pwd)"
 source "${SCRIPT_DIR}/../shared/ensure-artifactory-credentials.sh"
 
-PACKAGE_LOCATION=$1
+PACKAGE_LOCATION="${1}"
+PACKAGE_JSON="${PACKAGE_LOCATION}/package.json"
+PACKAGE_VERSION=$(cat "${PACKAGE_JSON}" | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[:,\",]//g;s/version//' | tr -d '[[:space:]]')
+PACKAGE_NAME=$(cat "${PACKAGE_JSON}" | grep name | head -1 | awk -F= "{ print $2 }" | sed 's/[:,\",]//g;s/name//' | tr -d '[[:space:]]')
 
-PACKAGE_JSON=$PACKAGE_LOCATION/package.json
-PACKAGE_VERSION=$(cat $PACKAGE_JSON | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[:,\",]//g;s/version//' | tr -d '[[:space:]]')
-PACKAGE_NAME=$(cat $PACKAGE_JSON | grep name | head -1 | awk -F= "{ print $2 }" | sed 's/[:,\",]//g;s/name//' | tr -d '[[:space:]]')
-
-if ! is_version_published $PACKAGE_NAME $PACKAGE_VERSION; then
-  if publish $PACKAGE_LOCATION; then
+if ! is_version_published "${PACKAGE_NAME}" "${PACKAGE_VERSION}"; then
+  if publish "${PACKAGE_LOCATION}"; then
     echo "Version \"$PACKAGE_VERSION\" of \"$PACKAGE_NAME\" published 🎉"
   else
-    echo "Publishing Version \"$PACKAGE_VERSION\" of \"$PACKAGE_NAME\" failed 😢"
+    echo "Publishing version \"$PACKAGE_VERSION\" of \"$PACKAGE_NAME\" failed 😢"
   fi
 else
   echo "Version \"$PACKAGE_VERSION\" of \"$PACKAGE_NAME\" is already published 🤷‍♂️"
